version: "3.9"
services:
  app:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
     - db
     - queues
  job_processor:
    build: ./job_processor
    ports:
      - "5000:5000"
    depends_on:
      - queues
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    env_file: .env
  queues:
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"
