version: "3.9"
# todo: add network so only app can see db, and only the services can see queues
services:
  #app:
  #  build: ./app
  #  env_file: ./app/.env
  #  ports:
  #    - "8000:8000"
  #  depends_on:
  #   - db
  #   - queues
  #worker:
  #  build: ./worker
  #  ports:
  #    - "5000:5000"
  #  depends_on:
  #    - queues
  #    - app
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    env_file: .env
  queues:
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"
