version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
#    depends_on:
#      - db
#      - queues
#  db:
#    image: "postgres:latest"
#    ports:
#      - "5432:5432"
#    env_file: .env
#  queues:
#    image: "rabbitmq:latest"
#    ports:
#      - "5672:5672"